[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev:all"
  port = 3000

[context.production]
  environment = {NEXT_PUBLIC_API_URL = "https://mahek-decorator.netlify.app/api"}

[context.preview]
  environment = {NEXT_PUBLIC_API_URL = "https://preview--mahek-decorator.netlify.app/api"}

[context.deploy-preview]
  environment = {NEXT_PUBLIC_API_URL = "https://deploy-preview--mahek-decorator.netlify.app/api"}
